global:
  scrape_interval: 15s

scrape_configs:
  - job_name: api
    static_configs:
      - targets: ["host.docker.internal:8000"]
    metrics_path: '/metrics'  # Asegure-se de que sua API expõe as métricas neste endpoint

  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090
